### ISSUE TITLE
Error with read_only=False

### ISSUE THREAD

**Issue by ryanwangl** [gunthercox/ChatterBot#1091]
when I set 'read_only' to False, the enter a query which is not in the existing statement library, the log throws error msg: "chatterbot.ext.django_chatterbot.models.DoesNotExist: Statement matching query does not exist."

Below is the screenshot of the django setting.py. According to the setting, if the confidence is below 0.6, it should trigger the predefined answer in low confidence adapter, but in my case, the chatbot didn't return any answer. I couldn't figure out where went wrong. Can anyone help on this? thanks!

![image](https://user-images.githubusercontent.com/33450142/33369929-ffb627ba-d530-11e7-9bd3-a3209f26ec18.png)

**Comment by taiwotman** [comment]
First, remove the 'treadonly' parameter except if you really need it.
 Second, you could try diffent threshold but a good value might start at 0.7

**Comment by taiwotman** [comment]
First, remove the 'readonly' parameter except really need it.
Second, you could try diffent threshold but a good value might start at 0.7.

**Comment by ryanwangl** [comment]
Hi taiwotman & vkosuri,

thank you very much for the reply!

I have commented out the 'read_only' and raised the threshold to 0.7, but still getting the same error msg.

I want to turn off the 'self-learning' feature by setting the 'read_only=True', but once I do that, the db.sqllite3 stopped capturing the user input. I just want the chatbot to response based on trained data and be able to capture user input. Is there a way I can do that? thanks!

**Comment by xiaolitang** [comment]
Similar issue for me..

**Comment by isaam14** [comment]
I have the same problem. I would like to record the user input of each conversation on a mongo database but I don't want the chat-bot to learn from it. How can I do that?

**Comment by vkosuri** [comment]
@isaam14 Have you seen this example https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py

**Comment by isaam14** [comment]
@vkosuri Thanks, yes I have. But the thing is, that example only works without the option read_only = True. And I don't want the bot to use the Statements from one conversation as Responses in another one, I only want it to use what it learned from the Corpora (and the Responses it gets from some Logic Adapters that I added). So I want to record the conversations (including the Responses that come from a Logic Adapter but aren't on the Corpora) APART from the set of statements the bot uses to respond.
Is that possible? If it hasn't been done before, which files do you think I should modify to achieve something like this?

**Comment by tushar1328** [comment]
@isaam14 @vkosuri  I too want to do the same. i added read_only=TRUE to chatbot, after executing the the code the chat now prints the input we give as training corpus does not create the database  #1327

**Comment by tushar1328** [comment]
@isaam14 I got a trick, you can use read_only = True in your main script but to train your corpus files you will need them to be execute from different file which will remove the ambiguity with **read_only** see the sample code below
### train.py

```
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
chatbot = ChatBot('tushar')

class Trainer :
    x=str(input("Do you want to Train the model ?\nType Y for Yes and N for No : "))
    if x =="Y"or x =="y" :
        chatbot.set_trainer(ChatterBotCorpusTrainer)
        chatbot.train("chatterbot.corpus.english")
    elif x == "N" or x =="n":
        pass
    
 ```
### bot.py 
```
from train import Trainer
--------------------Rest of your code here---------------
```

Try this, I did the same and it worked.

**Comment by vkosuri** [comment]
@tushar1328 glad to here your problem was resolved.

**Comment by isaam14** [comment]
Thank you @tushar1328 but I don't think we have the same problem. This doesn't solve mine.

**Comment by isaam14** [comment]
This kinda solves my problem. It saves the conversations as two lists of lists (one for the user statements, the other for the bot statements, and a date is saved with each statement).

uri = # the mongo URI
                                      
bot = ChatBot(
    'Bot-Bot',
    trainer = 'chatterbot.trainers.ChatterBotCorpusTrainer',
    storage_adapter = "chatterbot.storage.MongoDatabaseAdapter",
    database_uri = uri,
    logic_adapters = [
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.8,
            'default_response': 'Uhhhmmmm... I didn't understand, could you ask something else please?'
        }
    ],
    # no input adapters
    read_only = True
    )

bot.train("/path/to/the/corpora")
client = MongoClient(uri)
try:
    client.admin.command({'setParameter': 1, 'internalQueryExecMaxBlockingSortBytes': 44040192})
except OperationFailure:
    pass
database = client['chatbot-conversations-register']
conv = database['conversations']
conv_id = conv.insert_one({}).inserted_id
user_list = []
bot_list = []
print('Write something to start...')

while True:
    try:
        user_input = str(raw_input()) # I use python 2.7, I guess it would be only input() for python 3
        if user_input:
            user_input = user_input.decode('utf-8')
            user_list.append([user_input, datetime.utcnow()])
        bot_input = bot.get_response(Statement(user_input)).text
        bot_list.append([bot_input, datetime.utcnow()])
        print(bot_input)
    except(KeyboardInterrupt, EOFError, SystemExit):
        break
try:
    conv.update_one({ "_id" : conv_id },
                    { '$set':{'conv-user': user_list} })
except(EOFError, SystemExit):
    print('failed')

try:
    conv.update_one({ "_id" : conv_id },
                    { '$set':{'conv-bot': bot_list} })
except(EOFError, SystemExit):
    print('failed')

**Comment by gunthercox** [comment]
This issue should have been corrected in the latest release. Please let me know if this issue persists in version 1.0
