### ISSUE TITLE
Sentence Comparison Algorithms

### ISSUE THREAD

**Issue by Melvinroy** [gunthercox/ChatterBot#624]
Hi,

I am getting the following error when I am trying to use any of the sentence comparison algorithms.

![image](https://cloud.githubusercontent.com/assets/10074485/22812635/e562ee76-ef6b-11e6-9e6f-80edfc0fba82.png)

Since I am new to the development environment it is hard for my to figure it out. Could someone help me?

**Comment by vkosuri** [comment]
Swap response and comparison it will work

**Comment by Melvinroy** [comment]
![image](https://cloud.githubusercontent.com/assets/10074485/22813797/7f2b0c16-ef74-11e6-8125-e5b5dd247709.png)

Still I get the following error

**Comment by vkosuri** [comment]
You have to write like this‎```Pythonstatement_compsion_function = chatterbot.comparision.leventhsisresponse_selection_method = chatterbot.response_selection```                                                                                                                                     And also delete your database.db file‎. let me know if you are facing issue                                                                                                                                                                                                   Sent from my BlackBerry 10 smartphone.

**Comment by VanRH** [comment]
I've seen something like the above when I tried replacing my installed version(via pip install) with a downloaded zip (clone button). It seemed like using multiple logic adapters cause an inconsistency between statement and string as the type that was being passed around. One adapter expected a string as input and another one expected a statement object. 

I ended up just using BestMatch and LowConfidenceAdapter. 

Maybe this is similar to my issues?

**Comment by vkosuri** [comment]
@Melvinroy Did your problem was resolved?

@VanRH I think this was old problem. It is resolved now.

**Comment by Melvinroy** [comment]
@vkosuri : No its not working 
@VanRH : No the issue is not solved. When I downloaded the package from Github and ran the codes I was able to run multiple logic adapters for some time , but after sometime the error starts appearing.

At present I am using BestMatch and Low Confidence Adapter(thinking I can solve the issue in the forecoming days) . I am concentration on how to connect with Mongodb and one of the user interfaces(Hipchat, Glitter etc.)
